// <auto-generated />
namespace Vidly_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReleaseDateProperty_MovieModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReleaseDateProperty_MovieModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201712070103093_ReleaseDateProperty_MovieModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
